version: 2
jobs:
  build:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package-lock.json" }}
            - dependencies-
      - run: npm ci
      - save_cache:
          paths: [node_modules]
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: npm run build
      - persist_to_workspace: {root: ., paths: [.]}
  test:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: sudo npm install -g codecov c8
      - run: c8 npm test
      - run: c8 report --reporter=text-lcov > coverage.lcov
      - run: codecov
  test-client:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run test-client
  lint:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: npm run lint
  deploy:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - attach_workspace: {at: .}
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run: npm publish
  onBranch:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_BRANCH ]]; then exit 1; fi
  isTagged:
    docker: [{image: "circleci/node:lts"}]
    steps:
      - run: if [[ -z $CIRCLE_TAG ]]; then exit 1; fi
workflows:
  version: 2
  run-tests:
    jobs:
      - onBranch:
          filters:
            branches: {only: /.*/}
            tags: {ignore: /.*/}
      - build: {requires: [onBranch]}
      - test: {requires: [build]}
      - test-client: {requires: [build]}
      - lint: {requires: [build]}
  release:
    jobs:
      - isTagged:
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - build:
          requires: [isTagged]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - test:
          requires: [build]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - test-client:
          requires: [build]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - lint:
          requires: [build]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
      - deploy:
          requires: [test, test-client, lint]
          filters:
            branches: {ignore: /.*/}
            tags: {only: /^v.*/}
